version: '3.8'

services:
  product-service:
    build: ./product_service
    ports:
      - "8000:8080"
    volumes:
      - ./data:/data
    environment:
      - DATA_PATH=/data/Product_Information_Dataset.csv
      - FAISS_INDEX_PATH=/data/faiss_index

  order-service:
    build: ./order_service
    ports:
      - "8001:8080"
    volumes:
      - ./data:/data

  chat-service:
    build: ./chat_service
    ports:
      - "8002:8080"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
      - PERPLEXITY_API_KEY=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
    depends_on:
      - product-service
      - order-service
