
services:
  product-service:
    build: ./product_service
    ports:
      - "8000:8080"
    volumes:
      - ./data:/data
    environment:
      - DATA_PATH=/data/Product_Information_Dataset.csv
      - FAISS_INDEX_PATH=/data/faiss_index
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure

  order-service:
    build: ./order_service
    ports:
      - "8001:8080"
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure

  chat-service:
    build: ./chat_service
    ports:
      - "8002:8080"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
    depends_on:
      - product-service
      - order-service

networks:
  ecommerce_network:
    name: ecommerce_network
