# fly.toml app configuration file generated for ecommerce-order-service-morning-dawn-9468 on 2025-05-05T14:14:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecommerce-order-service-morning-dawn-9468'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '8080'

[[mounts]]
  source = 'order_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
