# fly.toml app configuration file generated for ecommerce-product-service-green-haze-6364 on 2025-05-05T13:52:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecommerce-product-service-green-haze-6364'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  DATA_PATH = '/data/Product_Information_Dataset.csv'
  FAISS_INDEX_PATH = '/data/faiss_index'
  PORT = '8080'

[[mounts]]
  source = 'product_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
